[package]
name = "pumpkin_project_maps"
version = "2.0.0"
edition = "2024"
repository = "https://github.com/VladTheJunior/pumpkin_project_maps"


[dependencies.serde]
version = "1.0.219"
features = ["derive"]

[profile.release]
strip = true
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"